### PR TITLE
Added fortls autoupdate during initialisation

### PR DESCRIPTION
**Pull request by gnikit**
The server will ping PyPi and check if a version is available greater
than the currently installed version. If an old version is detected
fortls will download the new version to the pip localtion of the
current Python distribution.

This should allow for fortls to be correctly installed most times.
Obviously if running from a directory structure that does not
adhere to how pip/conda install packages this might not work.

### CODE REVIEW

**Comment by band-a-prend** [comment]
@gnikit 
Could you please give a cue how to patch fortls for permanent disabling of update check without passing command line parameter? 

I disable update check for tests for networkles 
sandbox with
```
sed -i -e 's/"--incremental_sync",/"--incremental_sync", "--disable_autoupdate",/' test setup_tests.py
```
but I also would like to disable it for package installed into system directory too.
It's sufficient to add `default=True` value where option is specified in `interface.py`?

**Comment by gnikit** [comment]
Sorry I missed this @band-a-prend, I cannot in good consciousness recommend this, since historically it leads to people opening reports for already resolved issues simply because they run an outdated version of fortls. I don't see why you would want to run the dev tests in a networkless environment, the only reason to do that is if you want to contribute to fortls which you can easily do with 2 clicks in a browser using GitHub CodeSpaces.

**Comment by band-a-prend** [comment]
>  I don't see why you would want to run the dev tests in a networkless environment

This is just a specifics Gentoo Linux packaging process when tests are ran in networkless sandbox env to be sure of it's reproducibility, have no side effects, dependence of external service availability etc... and to posibility run tests on isolated systems without internet connection.

I will try to avoid store outdated versions in repository. I assume even if fortls unable to update due to permission restriction of system directory there will be no problems for further processing.

**Comment by gnikit** [comment]
This will potentially come back to haunt me but if you want to disable fortls version checking you can create a patch removing or constantly evaluating the if-conditional to False here:
https://github.com/fortran-lang/fortls/blob/833755e6d59c3e5dd58c786028ed288721b8efde/fortls/langserver.py#L203-L207

> run tests on isolated systems without internet connection.

One of the interface tests would fail in such an environment, because it actually tests the PyPi metadata fetching mechanism, but that shouldn't matter for Users, and yes you are correct, if internet access is missing or inadequate permissions are present, fortls will carry on.

**Pull request merged**
