### PR TITLE
fix #160 `intent(in out)` is parsed correctly

### LINKED ISSUE #160: Intent(inout) does not work with spaces between in and out
**Describe the bug**
`intent(in out)` is not parsed correctly. Edit REGEX expression.

### PR DESCRIPTION
**Pull request by JHenneberg**

### CODE REVIEW

**Comment by gnikit** [comment]
Hi @JHenneberg thanks for taking the time to do this. Looks good!

With regards to the tests I wouldn't worry too much. If you are having problems just let me know when you're done and I can add it.

**Comment by JHenneberg** [comment]
@gnikit the difficult part for me is that I do not know python and I dont know how to run the test on my local machine. Maybe you can point me in the right direction to be able to run the tests.

**Review by gnikit — APPROVED** [review]
Looks good. For future PRs you might want to do `pre-commit install`, you only need to do it once. After that it will run a bunch of checks and apply fixes to certain coding practices.

**Comment by gnikit** [comment]
> > > @gnikit the difficult part for me is that I do not know python and I dont know how to run the test on my local machine. Maybe you can point me in the right direction to be able to run the tests.
> > 
> > 
> > You can have a look in the Contributing document: https://github.com/gnikit/fortls/blob/master/CONTRIBUTING.md
> 
> face_with_spiral_eyes my fault. Pretty obvious.

No worries, I made a bit of a mess myself with the commit history with all the security checks GitHub imposes

**Pull request merged**
