### PR TITLE
feat: Change hover to use MarkupContent

### LINKED ISSUE #45: Change hover to use MarkupContent
The hover requests use the deprecated user interface `MarkedString[]`. We should change to `MarkupContent` which uses markdown to style the hover requests. we can then use our language ID to color our block [see](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#markupContentInnerDefinition)

### LINKED ISSUE #70: Add support for LaTex in docstrings
I am in the process of rewritting the documentation parsing to be able to handle more formats. I think it would be possible to attempt to convert LaTex expressions found in the documentation to LaTex output. This can be combined with #45 since using Markdown to display LaTex seems like the easiest approach.

### LINKED ISSUE #214: bug: type-bound procedure pointer mangled name while hovering
**Describe the bug**
hovering over `norm` yields incorrect name

**To Reproduce**

```
> fortls --debug_filepath tmp.f90 --debug_hover --debug_line 15 --debug_char 17
```

```log
Testing "textDocument/hover" request:
  File = "tmp.f90"
  Line = 15
  Char = 17

  Result:
=======
[{'language': 'fortran90', 'value': 'FUNCTION vector_nonorm(norm)\n!! Doc 2\n REAL(8) :: norm'}]
=======
```

```fortran
TYPE, EXTENDS(vector) :: scaled_vector
CONTAINS
  PROCEDURE :: norm => scaled_vector_norm !< Doc 3
END TYPE scaled_vector
```

image

### LINKED ISSUE #217: bug(parser): multiline scope registration assigns end of line not start of line as scope start
During parsing the `line_no` is advanced to the end of the multi-line (&) number, hence when objects are registered in the AST, the scope start is set to the end of the multi-line not the start.

This superficially solved #59

_Originally posted by @gnikit in https://github.com/gnikit/fortls/issues/59#issuecomment-1298275580_

### PR DESCRIPTION
**Pull request by gnikit**
MarkedString[] has been deprecated so we switch
to full Markdown syntax for hover messages

## Changes:

- Changes the hover signature of variables from "integer, pointer" --> "integer, pointer :: val"
- Changes the Signature help message for Functions/Subroutines to use Markdown

Fixes #45
Fixes #70 if client permits it (vs code does not allow mathjax in markdown)
Fixes #214
Fixes #217 

## TODO:

- [x] Fix doxygen parser. Parse `@param[in|out]` as --> `arg` -- desc'
- [ ] replace hardwired `fortran90` in objects.py to "{langid}" and then string.from(langid=self.hover_language)

### CODE REVIEW

**Comment by gnikit** [comment]
@plevold might want to have a look on this. I still need to fix the Doxygen parsing of docstrings

**Comment by plevold** [comment]
@gnikit looks very nice indeed! I've noticed two issues that would make it even better:

1. The argument documentation list gets put at the bottom. When I write long docstrings for procedures it's easy to end up in a situation where I don't see the signature when reading the argument documentation list. I'd suggest putting the list above the docstring.

2. Whitespace at the beginning of docstring lines gets trimmed. This makes code examples with indentation look weird. For example:

```fortran
!> Generate an error report with the given message as root cause.
!! Use this to create general application errors which don't need to be
!! identified programatically. See
!!
!! ### Example:
!! ```fortran
!! subroutine ask_hal_9000(error)
!!     use error_handling, only: error_t, fail
!!     class(error_t), intent(out) :: error
!!
!!     error = fail("I'm sorry Dave, I can't do that")
!! end subroutine
!! ```
pure module function fail_message(message) result(error)
    !> Message to fail with
    character(len=*), intent(in) :: message
    type(error_report_t) :: error
end function
```

Gets turned into this hover:
image

I checked and this behaviour is present in the current fortls release as well, but I'm not sure where the trimming takes place.

**Comment by gnikit** [comment]
> 1. The argument documentation list gets put at the bottom. When I write long docstrings for procedures it's easy to end up in a situation where I don't see the signature when reading the argument documentation list. I'd suggest putting the list above the docstring.

Even though I too agree that this is a more intuitive way to display documentation (having had my start with C++ where docs are on top), you will see that both the Python, C++, JS and TS extension display hover messages the same way. Not sure what the justification for this is but I would aim to keep it consistent. 


> 2. Whitespace at the beginning of docstring lines gets trimmed. This makes code examples with indentation look weird. For example:

We actually strip all code lines in a few places. It makes easier to parse if you don't have to worry about white spaces.

Then to create new lines in hover Markdown we use a combination of spaces and newline characters, else the docstring would be too spaced out.

In theory what you're saying should be relatively easy to fix only because it's the leading whitespace and not the trailing ones. Although reality might be a bit different, I'll have a look.

**Comment by plevold** [comment]
> you will see that both the Python, C++, JS and TS extension display hover messages the same way. Not sure what the justification for this is but I would aim to keep it consistent.

I had not noticed that! I agree that consistency is a good idea. Also, if somebody really want an argument list at the top they could just include it in the main docstring instead so I don't think it needs to be changed.

**Pull request merged**
