### PR TITLE
extended list of keywords

### PR DESCRIPTION
**Pull request by JHenneberg**
acc. to. Intel oneAPI Develeoper (p. 2246) for consistency. I left out the vendor specific keywords `AUTOMATIC` and  `STATIC`. 
Probably it is better to switch to a not vendor specific document for refernce for example `ISO_1539-1_Fortran_Standart_2018`

### CODE REVIEW

**Comment by gnikit** [comment]
Nice job @JHenneberg and thanks for the PR. Don't worry about the unittests I can fix them

**Comment by gnikit** [comment]
> Probably it is better to switch to a not vendor specific document for refernce for example `ISO_1539-1_Fortran_Standart_2018`

Do you have a link for the doc? From some quick googling I was only able to find this https://j3-fortran.org/doc/year/18/18-007r1.pdf

**Comment by JHenneberg** [comment]
> > Probably it is better to switch to a not vendor specific document for refernce for example `ISO_1539-1_Fortran_Standart_2018`
> 
> Do you have a link for the doc? From some quick googling I was only able to find this https://j3-fortran.org/doc/year/18/18-007r1.pdf

Yeah thats the one I got.

**Comment by gnikit** [comment]
@JHenneberg I am having a look now to see if the changes would be too many

**Comment by gnikit** [comment]
The problem with using the standard to update the keywords is that the keyword description is very obscure so we would ultimately have to go back to either GCC or Intel for a concise description

**Comment by JHenneberg** [comment]
> The problem with using the standard to update the keywords is that the keyword description is very obscure so we would ultimately have to go back to either GCC or Intel for a concise description

I am also fine with leaving it for now like this because of the workload. But if I would start from scratch I always would do it vendor inspecific.

**Comment by gnikit** [comment]
> > The problem with using the standard to update the keywords is that the keyword description is very obscure so we would ultimately have to go back to either GCC or Intel for a concise description
> 
> I am also fine with leaving it for now like this because of the workload. But if I would start from scratch I always would do it vendor inspecific.

I would not say that it is vendor specific. We still look at the standard when updating the keywords, it's a matter of clarity.

This
> Specifies that an object is allocatable

is a lot clearer than this
> A variable with the ALLOCATABLE attribute is a variable for which space is allocated during execution.

if GCC had an equally easy to access online doc of attributes I would probably use that instead

**Comment by gnikit** [comment]
Awesome, thanks for all the help. I also read the standard and added (hopefully) all the missing statements.

**Pull request merged**
