### PR TITLE
Allow running python -m fortls

### PR DESCRIPTION
**Pull request by awvwgk**
Add a `__main__.py` to allow running `python -m fortls`.

### CODE REVIEW

**Comment by awvwgk** [comment]
This pre-commit.ci autofix is quite useful to circumvent the first-time-contributor limitations... not that I plan to do anything malicious, but for running the CI on my patch it is invaluable.

**Comment by gnikit** [comment]
Does adding main.py mean that we should modify the entry_point of fortls?

**Comment by awvwgk** [comment]
> Does adding main.py mean that we should modify the entry_point of fortls?

No, they are independent from each other, the `entry_point` will be linked in `$PREFIX/bin/fortls` and is only available if `$PREFIX/bin` is in your `PATH`, while `__main__.py` allows running the language server if the fortls module is in the Python path, *e.g.* when installing in `~/.local` and not including `~/.local/bin` in your `PATH`.

**Comment by gnikit** [comment]
Great, thanks for the help. I suppose this has something to do with the brew packaging.

**Comment by gnikit** [comment]
I might have to add back the `fortls.py` script, in addition to testing it was also used as an entry_point for local testing with vscode i.e. I would set the path to "fortran.fortls.path": ".../fortls/fortls.py" to test certain features in large Fortran projects.

**Comment by awvwgk** [comment]
> I would set the path to "fortran.fortls.path": ".../fortls/fortls.py" to test certain features in large Fortran projects.

You should be able to replace this with `python -m fortls` in the same way I did for the test driver.

**Comment by gnikit** [comment]
> > I would set the path to "fortran.fortls.path": ".../fortls/fortls.py" to test certain features in large Fortran projects.
> 
> You should be able to replace this with `python -m fortls` in the same way I did for the test driver.

Vscode might (I don't remember) not permit that. Either way it's not very important for me and I have a few changes down the line that would make this a non-issue. As of now, there are solutions like pip install -e . or simply keeping a file like fortls.py somewhere locally.

**Comment by awvwgk** [comment]
> As of now, there are solutions like pip install -e . or simply keeping a file like fortls.py somewhere locally.

Editable install seems preferable, if you need to set a path, making `__main__.py` executable and using `fortls/fortls/__main__.py` as script should be an option as well.

**Pull request merged**
